version: "3.9"
services:
  db:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin2022
      - POSTGRES_DB=go_examples
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata: